[book]
authors = ["Benjamin Bannier"]
language = "en"
multilingual = false
src = "src"
title = "Introduction to Spicy"

[preprocessor.spicy-code]
command = "python3 scripts/mdbook-spicy-code"

[output.html.code.hidelines]
ruby = "!"
