[book]
authors = ["The Zeek developers"]
language = "en"
multilingual = false
src = "src"
title = "The Spicy Book"

# [preprocessor.spicy-code]
# command = "python3 scripts/mdbook-spicy-code"

[output.html.code.hidelines]
spicy = "###"
ruby = "###"

[output.linkcheck]
follow-web-links = true
