[book]
authors = ["Benjamin Bannier"]
language = "en"
multilingual = false
src = "src"
title = "The Spicy Book"

# [preprocessor.spicy-code]
# command = "python3 scripts/mdbook-spicy-code"

[output.html.code.hidelines]
ruby = "###"
